import type { PostComment } from "@/src/domain/post";
import type { CreateCommentInput, UpdateCommentInput } from "../dto";

/**
 * Builds a new persisted comment without performing I/O.
 *
 * @param input - Authorized and validated comment values.
 * @param id - Stable identifier generated by the composition layer.
 * @param timestamp - Creation timestamp.
 * @returns The persisted comment.
 */
export function createCommentRecord(
  input: CreateCommentInput,
  id: string,
  timestamp: string,
): PostComment {
  return {
    id,
    postId: input.postId,
    authorId: input.authorId,
    body: input.body,
    createdAt: timestamp,
    updatedAt: null,
  };
}

/**
 * Builds an updated comment when the requesting person owns it.
 *
 * @param comment - Current persisted comment.
 * @param input - Authorized replacement values.
 * @param timestamp - Update timestamp.
 * @returns The updated comment, or null when ownership does not match.
 */
export function updateCommentRecord(
  comment: PostComment,
  input: UpdateCommentInput,
  timestamp: string,
): PostComment | null {
  if (comment.id !== input.commentId || comment.authorId !== input.authorId) {
    return null;
  }

  return {
    ...comment,
    body: input.body,
    updatedAt: timestamp,
  };
}

/**
 * Removes a comment only when the requesting person owns it.
 *
 * @param comments - Current comment collection.
 * @param commentId - Comment identifier to remove.
 * @param authorId - Requesting person's identifier.
 * @returns The remaining comments and whether a comment was removed.
 */
export function deleteCommentRecord(
  comments: readonly PostComment[],
  commentId: string,
  authorId: string,
): { deleted: boolean; comments: readonly PostComment[] } {
  const remaining = comments.filter(
    (comment) => comment.id !== commentId || comment.authorId !== authorId,
  );

  return {
    deleted: remaining.length !== comments.length,
    comments: remaining,
  };
}
