import type { PersistedPost } from "@/src/domain/post";
import type {
  CreatePostInput,
  PostRecord,
  UpdatePostInput,
} from "../dto";

/**
 * Builds a new persisted Post without performing I/O.
 *
 * @param input - Authorized and validated Post values.
 * @param id - Stable identifier generated by the composition layer.
 * @param timestamp - Creation and update timestamp.
 * @returns The persisted Post record.
 */
export function createPostRecord(
  input: CreatePostInput,
  id: string,
  timestamp: string,
): PostRecord {
  return {
    id,
    type: input.type,
    authorId: input.authorId,
    subject: input.subject,
    dateTime: timestamp,
    body: input.body,
    createdAt: timestamp,
    updatedAt: timestamp,
    media: input.media,
    kidId: input.kidId,
    roomId: input.roomId,
  };
}

/**
 * Builds an updated persisted Post while preserving its creation timestamp.
 *
 * @param currentPost - Current persisted Post.
 * @param input - Authorized and validated replacement values.
 * @param timestamp - Update timestamp.
 * @returns The updated Post, or null when the author is not authorized.
 */
export function updatePostRecord(
  currentPost: PersistedPost,
  input: UpdatePostInput,
  timestamp: string,
): PostRecord | null {
  if (currentPost.authorId !== input.authorId) {
    return null;
  }

  return {
    ...currentPost,
    type: input.type,
    authorId: input.authorId,
    subject: input.subject,
    dateTime: timestamp,
    body: input.body,
    updatedAt: timestamp,
    media: input.media,
    kidId: input.kidId,
    roomId: input.roomId,
  };
}
